export const UPDATE_PAYMENT_TYPE    = 'UPDATE_PAYMENT_TYPE'
export const UPDATE_USER_INFO       = 'UPDATE_USER_INFO'
export const UPDATE_CARD_INFO       = 'UPDATE_CARD_INFO'
export const UPDATE_CEP             = 'UPDATE_CEP'
export const UPDATE_RECURRENCE      = 'UPDATE_RECURRENCE'
export const UPDATE_ERRORS          = 'UPDATE_ERRORS'
export const UPDATE_PLAN_TERMS      = 'UPDATE_PLAN_TERMS'
export const UPDATE_PLAN_ERRORS     = 'UPDATE_PLAN_ERRORS'